name: duktape4j

on:
  [push]
jobs:
  windows:
    name: windows
    runs-on: windows-2016
    if: "contains(toJSON(github.event.commits.*.message), '[build windows]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-python@v2
      name: add python to PATH
      with:
       python-version: '2.x'
       architecture: 'x64'
    - uses: actions/setup-java@v1
      name: configure Java 1.8
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
        cd native
        build-msvc.bat
      shell: cmd
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
      shell: cmd
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: duktape4j-windows
        path: src\main\resources\META-INF\duktape.dll
  mac:
    name: macos
    runs-on: macos-10.15
    if: "contains(toJSON(github.event.commits.*.message), '[build macos]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-python@v2
      name: add python to PATH
      with:
       python-version: '2.x'
       architecture: 'x64'
    - uses: actions/setup-java@v1
      name: configure Java 1.8
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
        cd native
        ./build-macos.sh
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: duktape4j-macos
        path: src/main/resources/META-INF/duktape.dylib
  centos:
    name: centos
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.commits.*.message), '[build centos]')"
    container: centos:7
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - name: Build
      run: |
        yum -y update
        yum -y group install "Development Tools"
        yum -y install wget
        yum -y install unzip
        yum -y install maven
        mkdir -p archive
        cd archive
        if [ ! -d "cmake" ]; then
          wget -q https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
          tar xfz cmake-3.17.3-Linux-x86_64.tar.gz
          mv cmake-3.17.3-Linux-x86_64/ cmake/
        fi
        export PATH=$PATH:$PWD/cmake/bin
        cd ..
        cd native
        ./build.sh
    - name: Test
      run: |
        mvn -q -B -DskipTests package
        mvn test
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: duktape4j-centos
        path: src/main/resources/META-INF/duktape.so